# Generated by Django 5.2.1 on 2025-05-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('data_nasterii', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudiuClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InregistrareMedicala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inregistrarii', models.DateField(auto_now_add=True)),
                ('observatii', models.TextField(blank=True)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacienti.pacient')),
                ('studiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacienti.studiuclinic')),
            ],
        ),
    ]
