# Generated by Django 5.2.1 on 2025-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inregistraremedicala',
            options={'verbose_name': 'Înregistrare medicală', 'verbose_name_plural': 'Înregistrări medicale'},
        ),
        migrations.AlterModelOptions(
            name='pacient',
            options={'verbose_name': 'Pacient', 'verbose_name_plural': 'Pacienți'},
        ),
        migrations.RemoveField(
            model_name='studiuclinic',
            name='data_sfarsit',
        ),
        migrations.AddField(
            model_name='studiuclinic',
            name='pacienti',
            field=models.ManyToManyField(related_name='studii', to='pacienti.pacient'),
        ),
        migrations.AlterField(
            model_name='studiuclinic',
            name='descriere',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studiuclinic',
            name='titlu',
            field=models.CharField(max_length=100),
        ),
    ]
