# Generated by Django 5.2.1 on 2025-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0002_alter_inregistraremedicala_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiuclinic',
            name='data_sfarsit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
