# Generated by Django 5.2.1 on 2025-05-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0003_studiuclinic_data_sfarsit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiuclinic',
            options={'verbose_name': 'Studiu clinic', 'verbose_name_plural': 'Studii clinice'},
        ),
    ]
